@extends('layouts.main.app')

@section('stylesheets')

@endsection

@section('content')

<section class="hero-wrap hero-wrap-2 mt-2" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <h1 class="mb-2 bread">1st Triemeseter</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section ftco-no-pt ftc-no-pb">
    <div class="container">
        <div class="row no-gutters">
            <ul>
                <li>
                    <p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Normal Changes:</strong></u></span></span></p>
                </li>
            </ul>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">While your first sign of pregnancy might have been a missed period, you can expect several other physical changes in the coming weeks, including:</span></span></p>
            <ul>
                <li>
                    <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Tender, swollen breasts</strong></u></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><strong>.</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">&nbsp;Soon after conception, hormonal changes might make your breasts sensitive or sore. The discomfort will likely decrease after a few weeks as your body adjusts to hormonal changes.</span></span></p>
                </li>
                <li>
                    <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Nausea with or without vomiting.</strong></u></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">&nbsp;Morning sickness, which can strike at any time of the day or night, often begins one month after you become pregnant. This might be due to rising hormone levels.</span></span></p>
                </li>
                <li>
                    <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Increased urination</strong></u></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><strong>.</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">&nbsp;You might find yourself urinating more often than usual. The amount of blood in your body increases during pregnancy, causing your kidneys to process extra fluid that ends up in your bladder.</span></span></p>
                </li>
                <li>
                    <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Fatigue.</strong></u></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">&nbsp;During early pregnancy, levels of the hormone progesterone soar &mdash; which can put you to sleep. </span></span></p>
                </li>
                <li>
                    <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Food cravings and aversions.</strong></u></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">&nbsp;When you're pregnant, you might become more sensitive to certain odors and your sense of taste might change. Like most other symptoms of pregnancy, food preferences can be chalked up to hormonal changes.</span></span></p>
                </li>
                <li>
                    <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Heartburn</strong></u></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><strong>.</strong></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">&nbsp;Pregnancy hormones relaxing the valve between your stomach and esophagus can allow stomach acid to leak into your esophagus, causing heartburn. </span></span></p>
                </li>
                <li>
                    <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Constipation.</strong></u></span></span><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">&nbsp;High levels of the hormone progesterone can slow the movement of food through your digestive system, causing constipation. Iron supplements can add to the problem. </span></span></p>
                </li>
            </ul>
            <p align="justify">&nbsp;</p>
            <p align="justify">&nbsp;</p>
            <ul>
                <li>
                    <p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>When to Visit Doctor:</strong></u></span></span></p>
                </li>
            </ul>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">Your first visit required at </span></span><span style="color: #202124;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">4 weeks. In fist trimester you have to at least 3 prenatal visit with a doctor. Per month at least 1 time visit required. According to WHO</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">Whether you choose a family doctor, obstetrician, nurse-midwife or other pregnancy specialist, your health care provider will treat, educate and reassure you throughout your pregnancy.</span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">Your first visit will focus on assessing your overall health, identifying any risk factors and determining your baby's gestational age. Your health care provider will ask detailed questions about your health history. Be honest. If you're uncomfortable discussing your health history in front of your partner, schedule a private consultation. Also expect to learn about first trimester screening for chromosomal abnormalities.</span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">After the first visit, you'll probably be asked to schedule checkups every four weeks for the first 32 weeks of pregnancy. However, you may require more or less frequent appointments, depending on your health and medical history.</span></span></p>
            <p align="justify">&nbsp;</p>
            <ul>
                <li>
                    <p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Complecations:</strong></u></span></span></p>
                </li>
            </ul>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>1. Vaginal Bleeding </strong></u></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;">"If you have bleeding and bad cramping similar to period&nbsp;</span><span style="font-size: large;"><strong>cramps</strong></span><span style="font-size: large;">, this can be a sign of threatened&nbsp;</span><span style="font-size: large;"><strong>miscarriage</strong></span><span style="font-size: large;">. If this is coupled with sharp, lower&nbsp;</span><span style="font-size: large;"><strong>abdominal pain</strong></span><span style="font-size: large;">, it may be a sign of&nbsp;</span><span style="font-size: large;"><strong>ectopic pregnancy</strong></span><span style="font-size: large;">," a serious complication that occurs when the fertilized egg implants outside the uterus, usually in the fallopian tubes.</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;"><strong>What to do</strong></span><span style="font-size: large;">: "Call your doctor. Your doctor will likely do an&nbsp;</span><span style="font-size: large;"><strong>ultrasound</strong></span><span style="font-size: large;">, an exam, and some&nbsp;</span><span style="font-size: large;"><strong>blood</strong></span><span style="font-size: large;">&nbsp;work based on your symptoms. Though most spotting or light bleeding may not be a serious problem, "you don&rsquo;t want to ignore it if it is associated with cramping, heavy bleeding, or&nbsp;</span><span style="font-size: large;"><strong>abdominal pain</strong></span><span style="font-size: large;">."</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;"><u>2. Excessive Nausea and Vomiting</u></span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;">It's normal to have some&nbsp;</span><span style="font-size: large;"><strong>nausea&nbsp;</strong></span><span style="font-size: large;">and vomiting during your&nbsp;</span><span style="font-size: large;"><strong>first trimester</strong></span><span style="font-size: large;">. Most pregnant women go through that. But if it's severe or makes you dehydrated, that's something to heed. If you can&rsquo;t keep any water or fluids down for more than 12 hours, call your doctor.</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;">Vomiting that interferes with your day-to-day activities can lead to&nbsp;</span><span style="font-size: large;"><strong>weight loss</strong></span><span style="font-size: large;">,&nbsp;</span><span style="font-size: large;"><strong>dizziness</strong></span><span style="font-size: large;">,&nbsp;</span><span style="font-size: large;"><strong>dehydration</strong></span><span style="font-size: large;">, and an imbalance of&nbsp;</span><span style="font-size: large;"><strong>electrolytes</strong></span><span style="font-size: large;">,&rdquo; Aziz says.</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;"><strong>What to do:&nbsp;</strong></span><span style="font-size: large;">Tell your doctor. You may need hospitalization to treat the&nbsp;</span><span style="font-size: large;"><strong>dehydration</strong></span><span style="font-size: large;">, and many&nbsp;</span><span style="font-size: large;"><strong>medications</strong></span><span style="font-size: large;">&nbsp;are available to control nausea.</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;"><strong>Bottom line:&nbsp;</strong></span><span style="font-size: large;">"</span><span style="font-size: large;"><strong>Nausea and vomiting</strong></span><span style="font-size: large;">&nbsp;are normal occurrences during&nbsp;</span><span style="font-size: large;"><strong>pregnancy</strong></span><span style="font-size: large;">, but the extremes can cause problems. The majority of women who have nausea and vomiting in their first trimester will go on to have normal, healthy pregnancies.</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;"><u>3. High Fever</u></span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;">A&nbsp;</span><span style="font-size: large;"><strong>fever</strong></span><span style="font-size: large;">&nbsp;greater than 101 degrees Fahrenheit or 38 degrees Celsius during pregnancy may be serious. It could be a sign of infection, which could affect the baby. </span><span style="font-size: large;"><strong>Fevers</strong></span><span style="font-size: large;">&nbsp;during pregnancy that are accompanied with&nbsp;</span><span style="font-size: large;"><strong>rash</strong></span><span style="font-size: large;">&nbsp;and&nbsp;</span><span style="font-size: large;"><strong>joint pain&nbsp;</strong></span><span style="font-size: large;">may be a sign of infection such as cytomegalovirus (</span><span style="font-size: large;"><strong>CMV</strong></span><span style="font-size: large;">), toxoplasma, and parvovirus. </span><span style="font-size: large;"><strong>CMV</strong></span><span style="font-size: large;">&nbsp;is the most common cause of congenital&nbsp;</span><span style="font-size: large;"><strong>deafness</strong></span><span style="font-size: large;">, and it is not as uncommon as we think</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;"><strong>What to do:&nbsp; </strong></span><span style="font-size: large;">Report any fever plus upper respiratory symptoms, body ache, and&nbsp;</span><span style="font-size: large;"><strong>flu</strong></span><span style="font-size: large;">-like symptoms or&nbsp;</span><span style="font-size: large;"><strong>rashes</strong></span><span style="font-size: large;">&nbsp;and&nbsp;</span><span style="font-size: large;"><strong>joint pain</strong></span><span style="font-size: large;">&nbsp;to your doctor. And get your yearly&nbsp;</span><span style="font-size: large;"><strong>flu vaccine</strong></span><span style="font-size: large;">.</span></span></span></p>
            <h2 class="western" align="justify"><span style="color: #000000;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>4. Vaginal Discharge and Itching</strong></u></span></span></span></h2>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;">Some vaginal discharge is normal. But in some cases, These may be signs of treatable infections or&nbsp;</span><span style="font-size: large;"><strong>sexually transmitted diseases</strong></span><span style="font-size: large;">&nbsp;that can have important consequences in pregnancy.</span><span style="font-size: large;"><strong>&nbsp;</strong></span><span style="font-size: large;">If it's an infection, it could harm the baby.</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;"><strong>What to do:&nbsp; </strong></span><span style="font-size: large;">Don't be shy. Let your ob-gyn know what is going on down there because if there's a problem, treating it could make a difference to your baby.</span></span></span></p>
            <h2 class="western" align="justify"><span style="color: #000000;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>5. Pain or Burning During Urination</strong></u></span></span></span></h2>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;">These can be signs of&nbsp;</span><span style="font-size: large;"><strong>bladder</strong></span><span style="font-size: large;">&nbsp;or&nbsp;</span><span style="font-size: large;"><strong>urinary tract infections</strong></span><span style="font-size: large;">, and if left untreated, they can lead to more serious illness, infection, pre-term&nbsp;</span><span style="font-size: large;"><strong>labor</strong></span><span style="font-size: large;">, and pre-term birth.</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;"><strong>What to do:&nbsp;</strong></span><span style="font-size: large;">If it's an infection, treating it can relieve your pain, and help assure a healthy pregnancy.</span></span></span></p>
            <h2 class="western" align="justify"><span style="color: #000000;"><u>&nbsp;<span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><strong>6.Leg or Calf Pain, or Swelling on One Side/ Severe Headache</strong></span></span></u></span></h2>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;">This won't happen in most pregnancies. But pregnancy does mean a greater chance of developing a blood clot. A blood clot in the&nbsp;</span><span style="font-size: large;"><strong>calf</strong></span><span style="font-size: large;">&nbsp;may lead to pain or swelling and can result in a blood clot that travels to the&nbsp;</span><span style="font-size: large;"><strong>lung</strong></span><span style="font-size: large;">, which could be fatal. A blood clot in the&nbsp;</span><span style="font-size: large;"><strong>brain</strong></span><span style="font-size: large;">&nbsp;may be heralded by a severe&nbsp;</span><span style="font-size: large;"><strong>headache</strong></span><span style="font-size: large;">. There are other possible causes of bad&nbsp;</span><span style="font-size: large;"><strong>headaches</strong></span><span style="font-size: large;">&nbsp;during pregnancy.</span></span></span></p>
            <p align="justify"><a name="_GoBack"></a> <span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;"><strong>What to do</strong></span><span style="font-size: large;">: If you have a history of&nbsp;</span><span style="font-size: large;"><strong>blood clots</strong></span><span style="font-size: large;">, or if you get a severe&nbsp;</span><span style="font-size: large;"><strong>headache</strong></span><span style="font-size: large;">, consult your doctor.</span></span></span></p>
            <h2 class="western" align="justify"><span style="color: #000000;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">7. </span></span></span><span style="color: #000000;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Flare-Ups of Chronic Diseases</strong></u></span></span></span></h2>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;">Women who have certain pre-existing medical conditions -- such as&nbsp;</span><span style="font-size: large;"><strong>thyroid</strong></span><span style="font-size: large;">&nbsp;disease,&nbsp;</span><span style="font-size: large;"><strong>diabetes</strong></span><span style="font-size: large;">,&nbsp;</span><span style="font-size: large;"><strong>high blood pressure</strong></span><span style="font-size: large;">,&nbsp;</span><span style="font-size: large;"><strong>asthma</strong></span><span style="font-size: large;">, and/or&nbsp;</span><span style="font-size: large;"><strong>lupus</strong></span><span style="font-size: large;">&nbsp;-- should note any changes in their condition during pregnancy.</span><span style="font-size: large;"><strong>&nbsp;</strong></span><span style="font-size: large;">If your underlying disease is flaring up or not well-controlled, it can have serious consequences for your health -- and your baby's.</span></span></span></p>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;">For example, if your&nbsp;</span><span style="font-size: large;"><strong>thyroid</strong></span><span style="font-size: large;">&nbsp;hormone is too high or low, you can be at an increased risk of miscarriage or if your&nbsp;</span><span style="font-size: large;"><strong>blood sugar levels</strong></span><span style="font-size: large;">&nbsp;are not tightly controlled, you may be at increased risk of miscarriage or fetal abnormalities. </span></span></span></p>
            <ul>
                <li>
                    <p align="center"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;"><u><strong>Food Habits &amp; Life style:</strong></u></span></span></p>
                </li>
            </ul>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">To help relieve nausea, avoid having an empty stomach. Eat slowly and in small amounts every one to two hours. Choose foods that are low in fat. Avoid foods or smells that make your nausea worse. Drink plenty of fluids. Foods containing ginger might help. Contact your health care provider if your nausea and vomiting is severe. Rest as much as you can. A healthy diet and exercise might increase your energy. To prevent heartburn, eat small, frequent meals and avoid fried foods, citrus fruits, chocolate, and spicy or fried foods. To prevent or relieve constipation, include plenty of fiber in your diet and drink lots of fluids, especially water and prune or other fruit juices. Regular physical activity also helps.</span></span></p>
            <ul>
                <li>
                    <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: large;">Pregnancy might leave you feeling delighted, anxious, exhilarated and exhausted &mdash; sometimes all at once. Even if you're thrilled about being pregnant, a new baby adds emotional stress to your life.</span></span></p>
                </li>
            </ul>
            <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="font-size: large;">It's natural to worry about your baby's health, your adjustment to parenthood and the financial demands of raising a child. If you're working, you might worry about how to balance the demands of family and career. You might also experience mood swings. What you're feeling is normal. Take care of yourself, and look to loved ones for understanding and encouragement. If your mood changes become severe or intense, consult your health care provider. So make sure you have good prenatal care and a healthy&nbsp;</span><span style="font-size: large;"><strong>diet</strong></span><span style="font-size: large;">, and get proper rest and take your&nbsp;</span><span style="font-size: large;"><strong>prenatal vitamins</strong></span><span style="font-size: large;">.</span></span></span></p>
            <p align="justify">&nbsp;</p>
            <p align="justify"><a name="_Hlk64154285"></a> </p>
            <p align="justify">&nbsp;</p>
            <p align="justify">&nbsp;</p>
        </div>

</section>



@endsection

@section('scripts')

@endsection